name: Lint and Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# lint and check formatting of python code
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install Ruff
        run: pip install ruff
      - name: Run Ruff
        run: ruff check entity_extractor/
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install Black
        run: pip install black
      - name: Run Black
        run: black --check --diff --fast  --no-color entity_extractor/
